// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CSCS
NumericMatrix CSCS(NumericMatrix S, NumericMatrix newL, double lambda, int maxitr, double tol);
RcppExport SEXP CSCS_CSCS(SEXP SSEXP, SEXP newLSEXP, SEXP lambdaSEXP, SEXP maxitrSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type newL(newLSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxitr(maxitrSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(CSCS(S, newL, lambda, maxitr, tol));
    return rcpp_result_gen;
END_RCPP
}
