# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gNM1 <- function(Gfill, p) {
    .Call('covariancegraph_gNM1', PACKAGE = 'covariancegraph', Gfill, p)
}

